language: android

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - yes | sdkmanager "platforms;android-28"
    - yes | sdkmanager "build-tools;26.0.2"
    - chmod +x gradlew
    - ./gradlew dependencies || true
    

android: 
    components:
        - tools
        - platform-tools
    
        - build-tools-26.0.2
        - extra-google-m2repository
        - extra-android-m2repository
        - android-21
        
        - sys-img-armeabi-v7a-android-26
    licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+

before_script:
    - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
script:
    - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
