language: android

before_install:
  - chmod +x gradlew

android: 
  components:
    - tools
    - platform-tools
    
    - build-tools-26.0.2
    - extra-google-m2repository
    - extra-android-m2repository
    - android-21
  licenses:
    - "android-28 Android SDK Platform 28"
    - "27.0.3 Android SDK Build-Tools 27.0.3"
    - ".*"
    - "*"
   
